name: tfsitescape
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.5.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.14.0+5
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  firebase_database: ^3.0.7
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage
  cloud_firestore: ^0.12.9+5
  path_provider:
  flushbar: ^1.10.4
  persistent_bottom_nav_bar: any
  get:
  geolocator: ^5.3.2+2
  weather: ^1.1.1
  weather_icons: 2.0.1
  flutter_mapbox_navigation:
  device_preview:
  mapbox_gl: 0.0.5
  percent_indicator: "^2.1.5"
  lazy_load_scrollview: 1.1.0
  fuzzy:
  image:
  crypto:
  camera:
  photo_view:
  esys_flutter_share:
  file_picker:
  flutter_image_compress: ^0.6.8
  image_editor: ^0.7.1
  http:
  permission_handler: ^5.0.1+1
  flutter_compass: '^0.4.1'
  qr_code_scanner:
    git:
      url: git://github.com/juliuscanute/qr_code_scanner.git
  adv_camera: ^1.1.1+1
  faro_torch: ^0.0.3
  ext_storage:
  ntp:
  shared_preferences:
  expandable:
  flutter_native_image:
  firebase_messaging:
  flutter_local_notifications:
  flutter_screenutil:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.2
  build_web_compilers: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - images/login.jpg
    - images/telstra.png
    - images/optus.png
    - images/nbn.png
    - images/vodafone.png
    - images/tpg.png
    - images/placeholder.png
    - images/login/hill.png
    - images/login/tower.png
    - images/login/cloud_top.png
    - images/login/cloud_bottom.png
    - images/login/logo.png
    - images/home/hill.png
    - images/home/tower.png
    - images/home/koalas.png
    - images/home/day.png
    - images/home/night.png
    - images/home/weather_clear.png
    - images/home/weather_foggy.png
    - images/home/weather_rainy.png
    - images/home/weather_stormy.png
    - images/home/weather_cloudy.png
    - images/home/weather_snowy.png
    - images/home/icon_scanner.png
    - images/home/icon_calculations.png
    - images/home/icon_reports.png
    - images/home/icon_menu.png
    - images/home/icon_help.png
    - images/home/divider.png


  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/Quicksand-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
          style: italic
          weight: 800
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
